### ISSUE TITLE
Add react-hook-form / mantine use-form for the filters panel

### ISSUE THREAD

**Issue by dipiash** [dipiash/nx-vite-react-ts-mantine-boilerplate#54]
**Is your feature request related to a problem? Please describe.**
Currently this repository doesn't use [react-hook-form](https://react-hook-form.com/) or [Mantine use-form ](https://mantine.dev/form/use-form/) and each value grab from the [state](https://github.com/dipiash/nx-vite-react-ts-mantine-boilerplate/blob/e7ee4d6291c1aef934d4e21e105b06798edc8e94/apps/main/src/GithubApp/GithubApp.tsx#L18).

**Describe the solution you'd like**
Need to add one of above form handling solution

**Additional context**
See the contributing [guide](https://github.com/dipiash/nx-vite-react-ts-mantine-boilerplate/blob/main/CONTRIBUTING.md).

**Comment by Malay-dev** [comment]
Hey @dipiash, I would like to work on this issue, Please assign it to me...

**Comment by dipiash** [comment]
Hi, @Malay-dev!

Done it. You are welcome.

**Comment by Malay-dev** [comment]
Thank you @dipiash... It was a great experience working with you... Thank you for your guidance... :innocent:

**Comment by dipiash** [comment]
@Malay-dev you are welcome?
