### ISSUE TITLE
Add link to LICENSE file into readme

### ISSUE THREAD

**Issue by dipiash** [dipiash/nx-vite-react-ts-mantine-boilerplate#59]
**Is your feature request related to a problem? Please describe.**
The repository has a license file but Readme doesn't contain the link on it

**Describe the solution you'd like**
Add section with title `License` and with content MIT is a link to license file

**Comment by imrtls00** [comment]
Sure! I'll submit the Pull Request.

**Comment by imrtls00** [comment]
@dipiash I've submitted #60 please check.
