### ISSUE TITLE
Add tests type checking for main app

### ISSUE THREAD

**Issue by dipiash** [dipiash/nx-vite-react-ts-mantine-boilerplate#61]
**Is your feature request related to a problem? Please describe.**
In `apps/main/project.json` file the command `"type-check"` haven't action to check the types in test files

**Describe the solution you'd like**
Need to add second part of command in commands section: ` && tsc --project tsconfig.spec.json --noEmit`

**Additional context**
See the contributing [guide](https://github.com/dipiash/nx-vite-react-ts-mantine-boilerplate/blob/main/CONTRIBUTING.md).

**Comment by adripo** [comment]
Hi, I am working on this issue

**Comment by adripo** [comment]
@dipiash Can you please run the check on the PR?
